import { Router } from 'express';
import healthRouter from './health.router.js';
import authRouter from './auth/auth.router.js';
import rolesRouter from './auth/roles.router.js';
import customerRouter from './customers/customers.router.js';
import productRouter from './products/products.router.js';
import orderRouter from './orders/orders.router.js';
import importsRouter from './imports/imports.router.js';
import exportsRouter from './exports/exports.router.js';
import integrationRouter from './integrations/integration.router.js';
import webhookRouter from './integrations/webhook.router.js';
import syncRouter from './integrations/sync.router.js';
import cronRouter from './cron/cron.router.js';
import segmentRouter from './segments/segment.router.js';
import notificationRouter from './notifications/notification.router.js';
import templateRouter from './templates/template.router.js';
import campaignRouter from './campaigns/campaign.router.js';
import trackingRouter from './campaigns/tracking.router.js';
import unsubscribeRouter from './campaigns/unsubscribe.router.js';
import messagingRouter from './messaging/messaging.router.js';
import paymentRouter from './payments/payment.router.js';
import ticketRouter from './tickets/ticket.router.js';
import auditRouter from './audit/audit.router.js';
import reportRouter from './reports/report.router.js';
import { getRateLimiter, getAuthLimiter } from '../config/ratelimit.config.js';

const router = Router();
router.use('/health', healthRouter);
router.use(getRateLimiter());

router.use('/auth', getAuthLimiter());
router.use('/auth', authRouter);
router.use('/roles', rolesRouter);
router.use('/customers', customerRouter);
router.use('/products', productRouter);
router.use('/orders', orderRouter);
router.use('/imports', importsRouter);
router.use('/exports', exportsRouter);
router.use('/integrations', integrationRouter);
router.use('/webhooks', webhookRouter);
router.use('/integrations', syncRouter);
router.use('/cron', cronRouter);
router.use('/segments', segmentRouter);
router.use('/notifications', notificationRouter);
router.use('/templates', templateRouter);
router.use('/campaigns', campaignRouter);
router.use('/messaging', messagingRouter);
router.use('/payments', paymentRouter);
router.use('/tickets', ticketRouter);
router.use('/audit-logs', auditRouter);
router.use('/reports', reportRouter);
router.use('/track', trackingRouter);
router.use('/unsubscribe', unsubscribeRouter);

export default router;
